package com.tasp1.pocketpal.ui.theme

import androidx.compose.ui.graphics.Color

object PpLight {
    val Primary = Color(0xFF1A1A1A)
    val OnPrimary = Color(0xFFFFFFFF)
    val PrimaryContainer = Color(0xFFE8E6E1)
    val OnPrimaryContainer = Color(0xFF1A1A1A)
    val Secondary = Color(0xFF5B6CFF)
    val OnSecondary = Color(0xFFFFFFFF)
    val SecondaryContainer = Color(0xFFE8E8EC)
    val OnSecondaryContainer = Color(0xFF2A2A2E)
    val Tertiary = Color(0xFFC4785A)
    val Error = Color(0xFFD1433B)
    val Background = Color(0xFFF7F6F3)
    val OnBackground = Color(0xFF1A1A1A)
    val Surface = Color(0xFFFFFFFF)
    val OnSurface = Color(0xFF1A1A1A)
    val SurfaceVariant = Color(0xFFEFEDE8)
    val OnSurfaceVariant = Color(0xFF6B6B6B)
    val Outline = Color(0xFFE0DED8)
    val OutlineVariant = Color(0xFFD0CEC8)
    val UserBubble = Color(0xFFE8E6E1)
    val AssistantBubble = Color(0x00000000)
    val InputBar = Color(0xFFFFFFFF)
    val Placeholder = Color(0xFF9A9A9A)
    val AccentPeach = Color(0xFFC4785A)
}

object PpDark {
    val Primary = Color(0xFFEDEDED)
    val OnPrimary = Color(0xFF121212)
    val PrimaryContainer = Color(0xFF2A2A2A)
    val OnPrimaryContainer = Color(0xFFEDEDED)
    val Secondary = Color(0xFF9AA6FF)
    val OnSecondary = Color(0xFF121212)
    val Tertiary = Color(0xFFE0A090)
    val Error = Color(0xFFFF6B63)
    val Background = Color(0xFF121212)
    val OnBackground = Color(0xFFEDEDED)
    val Surface = Color(0xFF1C1C1C)
    val OnSurface = Color(0xFFEDEDED)
    val SurfaceVariant = Color(0xFF2A2A2A)
    val OnSurfaceVariant = Color(0xFFB0B0B0)
    val Outline = Color(0xFF3A3A3A)
    val OutlineVariant = Color(0xFF4A4A4A)
    val UserBubble = Color(0xFF2A2A2A)
    val AssistantBubble = Color(0x00000000)
    val InputBar = Color(0xFF1C1C1C)
    val Placeholder = Color(0xFF7A7A7A)
    val AccentPeach = Color(0xFFE0A090)
}
